In [1]:
from qutip import *
import numpy as np

In [2]:
#Z operator 
#sigmaz()

In [3]:
Qobj()

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

In [69]:
#create 5 qubits
#do this in a loop later
q1 = basis(2,0)
q2 = basis(2, 0)
q3 = basis(2, 0)
q4 = basis(2, 0)
q5 = basis(2, 0)

In [98]:
qub_dict = {'q1': q1, 'q2':q2, 'q3':q3, 'q4':q4, 'q5':q5}

In [99]:
n = 5    

In [100]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [101]:
#now we define sigx1

sigx1 = sigmax()*qub_dict['q1'] 
for i in range(2,6):
    sigx1 = tensor(sigx1, qub_dict['q' + str(i)])

In [102]:
sigx1

Quantum object: dims = [[2, 2, 2, 2, 2], [1, 1, 1, 1, 1]], shape = (32, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [103]:
sigx_dict = {}

In [104]:
for i in range(1, 5):
    prod = q1
    for j in range(2,6):
        if j == i + 1:
            q_w_pauli = sigmax()*qub_dict['q' + str(i)]
            prod = tensor(prod, q_w_pauli)
        else :
            prod = tensor( prod, qub_dict['q' + str(j)])
    sigx_dict['sigx' + str(i+1)] = prod

In [92]:
sigx_dict['sigx1']= sigx1

In [93]:
sigx_dict['sigx4']

Quantum object: dims = [[2, 2, 2, 2, 2], [1, 1, 1, 1, 1]], shape = (32, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [95]:
( sigx_dict['sigx1'] + sigx_dict['sigx3'] + sigx_dict['sigx4'] + sigx_dict['sigx5']).unit()

Quantum object: dims = [[2, 2, 2, 2, 2], [1, 1, 1, 1, 1]], shape = (32, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [96]:
HB = 0
for sigx in sigx_dict.keys():
    HB += -1.0*sigx_dict[sigx]

In [97]:
HB

Quantum object: dims = [[2, 2, 2, 2, 2], [1, 1, 1, 1, 1]], shape = (32, 1), type = ket
Qobj data =
[[-5.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]